server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    hostname: discovery-service
    prefer-ip-address: true