server:
  port: 9002

spring:
  application:
    name: contact-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    hostname: discovery-service
    prefer-ip-address: true
